# Site settings
title: ROAD Framework
email: your-email@domain.com
description: "ROAD – Rapid Objective-C Applications Development"
baseurl: "/road-ios-framework"
url: "https://github.com/epam/road-ios-framework"
twitter_username: ROADFramework
github_username:  epam

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments